site_name: Test Book

theme:
  name: material
  feature:
    tabs: true

markdown_extensions:
  - footnotes

extra:
  search:
    language: 'ja'

nav:
  - Home: index.md
  - Contents:
    - One: one.md
    - Two: two.md
    - Three: three.md
